FROM phil40/speechtotext-kaldi:latest

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONPATH=.

RUN apt -y update
RUN apt install -y wget build-essential libreadline-gplv2-dev libncursesw5-dev \
                        libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev \
                        libbz2-dev libffi-dev zlib1g-dev

RUN wget https://www.python.org/ftp/python/3.9.7/Python-3.9.7.tgz
RUN tar xzf Python-3.9.7.tgz
RUN cd Python-3.9.7 && ./configure --enable-optimizations && make install

RUN update-alternatives --install /usr/bin/python python /usr/local/bin/python3.9 1

RUN mkdir -p /config
ADD /config/requirements.txt /config/

RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python get-pip.py
RUN pip install -r /config/requirements.txt
RUN mkdir -p /speechtotext-api
COPY assets /assets

WORKDIR /speechtotext-api
